# Generated by Django 2.2 on 2019-05-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
